### ISSUE TITLE
Connettività uffici vs data center e strategia evolutiva

### ISSUE THREAD

**Issue by spiunno** [italia/pianotriennale-ict-doc#33]
Il capitolo 3.2 relativo alla connettività dovrebbe indicare una strategia differenziata per i diversi tipi di connettività:
-- uffici che hanno il CED in casa (caso che dovrebbe progressivamente sparire)
-- branch-office
-- data center / PSN
e/o suggerire come la topologia di rete (e di firewall, etc) va cambiata nel momento in cui il CED non è più in ufficio.

**Comment by pdavide** [comment]
Chiusa a seguito della pubblicazione della [versione 2019-2021 del Piano Triennale](https://docs.italia.it/italia/piano-triennale-ict/pianotriennale-ict-doc/it/2019-2021/).
