### ISSUE TITLE
Chiarimenti su "Cloud della PA"

### ISSUE THREAD

**Issue by spiunno** [italia/pianotriennale-ict-doc#34]
Sul forum la maggioranza delle richieste di chiarimento è relativa al significato del Cloud della PA
Il capitolo 3.1 richiede una migliore spiegazione di questo punto

**Comment by pdavide** [comment]
Chiusa a seguito della pubblicazione della [versione 2019-2021 del Piano Triennale](https://docs.italia.it/italia/piano-triennale-ict/pianotriennale-ict-doc/it/2019-2021/).
