### ISSUE TITLE
riferimento ad ANPA

### ISSUE THREAD

**Issue by jobonaf** [italia/pianotriennale-ict-doc#48]
https://pianotriennale-ict.readthedocs.io/it/latest/doc/06_ecosistemi.html#scenario-attuale
si fa riferimento ad ANPA, sostituita dal 1999 da APAT, che a sua volta - unita ad INFS e ICRAM - dal 2008 è ISPRA

**Comment by gvarisco** [comment]
Grazie mille per il contributo, @jobonaf. Ho preparato le modifiche necessarie nella PR #49.

**Comment by pdavide** [comment]
Chiusa a seguito della pubblicazione della [versione 2019-2021 del Piano Triennale](https://docs.italia.it/italia/piano-triennale-ict/pianotriennale-ict-doc/it/2019-2021/).
