### ISSUE TITLE
Inserirei link a "ACCORDO DI PARTENARIATO 2014-2020"

### ISSUE THREAD

**Issue by aborruso** [italia/pianotriennale-ict-doc#53]
Nel capitolo "Allegato 5: Paniere dataset open data" si fa riferimento all'"ACCORDO DI PARTENARIATO 2014-2020".

Gli metterei il link al documento con l'accordo, nel [punto in cui si cita](https://hyp.is/FhD7bCO4EemZqQPkeVn1gw/docs.italia.it/italia/piano-triennale-ict/pianotriennale-ict-doc/it/stabile/doc/allegati/5_paniere-dataset-open-data.html).

Saluti

**Comment by pdavide** [comment]
Chiusa a seguito della pubblicazione della [versione 2019-2021 del Piano Triennale](https://docs.italia.it/italia/piano-triennale-ict/pianotriennale-ict-doc/it/2019-2021/).
