### ISSUE TITLE
indice ripetuto 2 volte nella sezione a sinistra

### ISSUE THREAD

**Issue by cirospat** [italia/pianotriennale-ict-doc#59]
salve
ho notato che nella sezione di sinistra del Piano 2019-21 l'indice è ripetuto due volte.
![image](https://user-images.githubusercontent.com/3757525/54187603-44284980-44ae-11e9-8879-abad573e5073.png)

Praticamente dopo il capitolo **13. Indicazioni per le pubbliche amministrazioni**  riprende di nuovo il capitolo **1. Il Piano Triennale per l’informatica nella Pubblica Amministrazione**.

Infatti questo errore rende tutte le pagine molto lunghe.

Credo sia un errore nell'impostazione di qualche file di configurazione.

**Comment by pdavide** [comment]
Grazie @cirospat, provvedo a fixare il bug.

**Comment by cirospat** [comment]
ok mi fa piacere essere stato d'aiuto.
Ormai con i formati `Read the Docs` ho un certo occhio ;)

**Comment by pdavide** [comment]
Fixed.
