### ISSUE TITLE
Obiettivi accessibilità: non vi siete persi un pezzo?

### ISSUE THREAD

**Issue by jdeyla** [italia/pianotriennale-ict-doc#62]
Ciao
ho letto degli obiettivi
https://docs.italia.it/italia/piano-triennale-ict/pianotriennale-ict-doc/it/2019-2021/09_strumenti-per-la-generazione-e-la-diffusione-di-servizi-digitali.html#id2

**Ma non vi siete persi per strada il pezzo più importante?**

AGID non deve in realtà assolvere gli obblighi della legge (definire i requisiti, definire l’obbligo sproporzionato, ecc.)

Parlate solo di adeguare i siti alla direttiva.
Non è altro il lavoro da fare in realtà?

**Comment by pdavide** [comment]
Grazie @jdeyla, forse il luogo più adatto per questo tipo di discussione potrebbe essere il [forum](https://forum.italia.it).
Qui su GitHub non ci sarebbero molti interlocutori.
Se sei d’accordo chiudo la issue.

**Comment by jdeyla** [comment]
giustissimo. é che non era direttamente collegato...

Il ven 15 mar 2019, 16:13 Davide Porrovecchio <notifications@github.com> ha
scritto:
